// Generated by CoffeeScript 1.7.1
(function() {
  var Barf, Chuck, Derp, Hurl,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Barf = (function() {
    function Barf() {}

    Barf.prototype.hi = 'hi';

    return Barf;

  })();

  Hurl = (function(_super) {
    __extends(Hurl, _super);

    function Hurl() {
      return Hurl.__super__.constructor.apply(this, arguments);
    }

    Hurl.prototype.hi = 'ralph';

    return Hurl;

  })(Barf);

  Chuck = (function(_super) {
    __extends(Chuck, _super);

    function Chuck() {
      return Chuck.__super__.constructor.apply(this, arguments);
    }

    Chuck.prototype.hi = 'UP';

    return Chuck;

  })(Hurl);

  Derp = (function() {
    function Derp() {}

    Derp.prototype.hi = 'no';

    return Derp;

  })();

  module.exports = {
    Barf: Barf,
    Hurl: Hurl,
    Chuck: Chuck,
    Derp: Derp
  };

}).call(this);
